modules:
  tag-item:
    enabled: true
    tag-block: FLETCHING_TABLE
    tag-format: "&7#{player}"

  where-my-frame:
    enabled: true
    permission: "cookiepl.command.wmf"
    damagingShears: true
    allowEmptyItemFrame: false

  air-sword:
    enabled: true
    cooldown-ticks: 10

  fun-commands:
    enabled: true
    permission-fart: "cookiepl.command.fart"
    permission-spit: "cookiepl.command.spit"
    fart:
      enabled: true
      cooldown-seconds: 30
    spit:
      enabled: true
      cooldown-seconds: 5
    messages:
      cooldown: "&cPlease wait before using this command again."
      players-only: "&cThis command can only be used by players."
      no-permission: "&cYou do not have permission to use this command."

  door-knock:
    enabled: true
    text-display:
      enabled: true
      text: "&f* knocks on the door *"
      duration-ticks: 20
    cooldown-seconds: 1

  police-batons:
    enabled: true
    fbi-baton:
      display-name: "&9FBI Baton"
      custom-model-data: 101
      effects:
        darkness:
          amplifier: 2
          duration-seconds: 5
        slowness:
          amplifier: 2
          duration-seconds: 5
      message: "&6Player &e{player} &6was lightly stunned."
    electroshock-baton:
      display-name: "&9FBI Electroshock Baton"
      custom-model-data: 102
      effects:
        darkness:
          amplifier: 10
          duration-seconds: 7
        slowness:
          amplifier: 10
          duration-seconds: 7
      sit-duration-seconds: 7
      message: "&6Player &e{player} &6was heavily stunned."

  player-heads:
    enabled: true
    drop-chance: 100.0
    cooldown-seconds: 3
    bypass-permission: "cookiepl.playerheads.bypass"
    head-name-format: "&f{player}'s Head"

  hookah:
    enabled: true
    effect-duration-seconds: 3
    overdose-threshold: 8.0
    level-increase: 1.0
    level-decrease-per-second: 0.2
    overdose-level-decrease-per-second: 4.2
    smoke-particle-count: 15

  police-system:
    enabled: true
    permission: "cookiepl.police.use"
    max-cuff-distance: 20.0
    physics:
      min-distance: 2.0
      max-distance: 4.0
      pull-force: 0.3
      prevent-wall-dragging: true
    handcuffs-item:
      material: "LEAD"
      display-name: "&fHandcuffs"
      custom-model-data: 0
    baton-item:
      material: "BLAZE_ROD"
      display-name: "&cPolice Baton"
      custom-model-data: 0
    nock:
      duration-seconds: 10
      message: "&aYou have stunned player {player}!"
      not-stunned-message: "&cTarget player is not stunned."
    cuff:
      message: "&aYou have cuffed player {player}!"
      uncuff-message: "&ePlayer {player} has been released!"
    emote-commands:
      start-cuff: "emotes play 'Руки за спину' {player} true"
      stop-cuff: "emotes stop {player}"

  slap:
    enabled: true
    cooldown-seconds: 3
    pat-chance: 90.0
    messages:
      action-bar: "&6 <- {player} ->"
      pat-sender: "&6You patted {player} on the shoulder!"
      pat-receiver: "&6{player} patted you on the shoulder!"
      slap-sender: "&6You slapped {player} on the ass!"
      slap-receiver: "&6{player} slapped you on the ass!"

  throwable-stones:
    enabled: true
    stone-item:
      display-name: "&6Stone"
      lore:
        - "&7Press &f&oQ &7to throw"
    throw-power:
      base: 1.0
      sneaking: 0.4
      sprinting: 1.3
      jumping: 1.3
      sprinting-jumping: 1.5
    physics:
      gravity: 0.04
      bounce-modifier: 0.35
      damage-per-block-speed: 1.0
      remove-delay-ticks: 200

  resize:
    enabled: true
    permission: "cookiepl.resize"
    permission-extended: "cookiepl.resize.extended"
    permission-others: "cookiepl.resize.others"
    permission-bypass-cooldown: "cookiepl.resize.bypass.cooldown"
    permission-reload: "cookiepl.resize.reload"
    default-min-scale: 0.8
    default-max-scale: 1.15
    extended-min-scale: 0.0625
    extended-max-scale: 16.0
    cooldown-seconds: 30
    resize-steps: 20
    messages:
      prefix: "&d[&5Resize&d] "
      usage: "&cUsage: /resize <scale> [player]"
      reloaded: "&aPlugin configuration reloaded. Use /cookiepl reload."
      player-not-found: "&cPlayer '{player}' not found."
      invalid-number: "&cInvalid number format."
      scale-range: "&cScale must be between {min} and {max}."
      cooldown: "&cYou must wait {time} seconds before using this command again."
      resized: "&aSuccessfully resized to {scale}."
      resized-other: "&aSuccessfully resized {player} to {scale}."
      players-only: "&cThis command can only be used by players."
      no-permission: "&cYou do not have permission to use this command."

  anti-elytra:
    enabled: true
    mode: "blacklist"
    worlds:
      - "world_the_end"
    bypass-permission: "cookiepl.antielytra.bypass"
    feedback:
      message: "&cElytra flight is disabled in this world."
      sound: "ENTITY_ENDERMAN_TELEPORT"
      particle: "SMOKE_NORMAL"

  afk-system:
    enabled: true
    afk-time-seconds: 300
    indicator:
      enabled: true
      text: "&e⌛"
      y-offset: 0.5
    immobility:
      enabled: true
      prevent-block-break: true
    invulnerability:
      enabled: true
    no-hunger:
      enabled: true
    sleep-ignore:
      enabled: true
    placeholder:
      afk-symbol: " &e[AFK]"

logging:
  enabled: true
  log-level: "INFO"