name: CookiePl
version: 1.0.0
main: com.leir4iks.cookiepl.CookiePl
api-version: '1.21'
author: leir4iks
folia-supported: true
softdepend: [PlaceholderAPI]

commands:
  cookiepl:
    description: Main command for the CookiePl plugin.
    usage: /<command> <reload|fixinvulnerable>
    permission: cookiepl.command.base
    permission-message: "You do not have permission to use this command."
  wheremyframe:
    description: WhereMyFrame module command.
    usage: /<command> <info>
    aliases: [wmf]
    permission: cookiepl.command.wmf
    permission-message: "You do not have permission to use this command."
  fart:
    description: Makes a fart sound and effect.
    usage: /<command>
    permission: cookiepl.command.fart
    permission-message: "You do not have permission to use this command."
  spit:
    description: Spits a stream of particles.
    usage: /<command>
    permission: cookiepl.command.spit
    permission-message: "You do not have permission to use this command."
  police:
    description: Police system commands.
    usage: /<command> give <item>
    permission: cookiepl.police.use
    permission-message: "You do not have permission to use this command."
  resize:
    description: Change the size of yourself or another player.
    usage: /resize <scale> [player]
    aliases: [res]
    permission: cookiepl.resize
    permission-message: "You do not have permission to use this command."