name: CookiePl
version: 1.0.0
main: com.leir4iks.cookiepl.CookiePl
api-version: '1.21'
author: leir4iks
folia-supported: true
softdepend: [PlaceholderAPI, DiscordSRV, SkinsRestorer, LuckPerms, squaremap]

commands:
  cookiepl:
    description: Main command for the CookiePl plugin.
    usage: /<command> <reload>
  wheremyframe:
    description: WhereMyFrame module command.
    usage: /<command> <info>
    aliases: [wmf]
  fart:
    description: Makes a fart sound and effect.
    usage: /<command>
  spit:
    description: Spits a stream of particles.
    usage: /<command>
  police:
    description: Police system commands.
    usage: /<command> give <item>
  resize:
    description: Change the size of yourself or another player.
    usage: /resize <scale> [player]
    aliases: [res]
  afk:
    description: Toggle AFK status.
    usage: /<command>
  profile:
    description: Open profile settings.
    usage: /<command>
  hat:
    description: Wear the item in your hand as a hat.
    usage: /<command> [remove|off|0]

permissions:
  cookiepl.command.base:
    description: Allows use of /cookiepl.
    default: false
  cookiepl.command.reload:
    description: Allows reloading CookiePl.
    default: false
  cookiepl.command.wmf:
    description: Allows use of /wheremyframe.
    default: false
  cookiepl.command.fart:
    description: Allows use of /fart.
    default: false
  cookiepl.command.spit:
    description: Allows use of /spit.
    default: false
  cookiepl.command.afk:
    description: Allows use of /afk.
    default: false
  cookiepl.police.use:
    description: Allows use of /police and police interactions.
    default: false
  cookiepl.resize:
    description: Allows use of /resize.
    default: false
  cookiepl.resize.extended:
    description: Allows extended resize range.
    default: false
  cookiepl.resize.others:
    description: Allows resizing other players.
    default: false
  cookiepl.resize.reload:
    description: Allows resize reload subcommand.
    default: false
  cookiepl.resize.bypass.cooldown:
    description: Allows bypassing resize cooldown.
    default: false
  cookiepl.playerheads.bypass:
    description: Prevents the player head drop mechanic from affecting the player.
    default: false
  cookiepl.antielytra.bypass:
    description: Bypasses anti-elytra restrictions.
    default: false
  cookiepl.antigrief.bypass:
    description: Bypasses anti-grief restrictions.
    default: false
  cookiepl.hat.ignore-binding:
    description: Allows ignoring binding curse restrictions in /hat.
    default: false
